title: "m68kplugin"
description: Motorola 68000 Series Assembly Language Support for IntelliJ-based IDEs
remote_theme: pmarsceill/just-the-docs

aux_links:
  "GitHub":
    - "//github.com/YannCebron/m68kplugin"