name: CI

on:
  push:
  pull_request:
    types: [opened, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk8
    steps:
    - uses: actions/checkout@v2
    - name: Setup Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Run tests
      run: ./gradle check

    - name: Build the plugin using Gradle
      run: ./gradle buildPlugin
    - name: Verify Plugin on IntelliJ Platforms
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.1
      with:
        ide-versions: |
          ideaIC:2019.3
          ideaIC:2020.1
    - name: Get log file path and print contents
      run: |
        echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}