name: Build & Test
on: [push, pull_request]

jobs:

  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest

    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4


  build:
    name: Build, Test & Validate Plugin
    needs: gradleValidation
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk8
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
      artifact: ${{ steps.properties.outputs.artifact }}

    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run plugin tests
        run: gradle check

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          CHANGELOG="$(./gradlew getChangelog --unreleased --no-header --console=plain -q)"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          ARTIFACT="m68kplugin-${VERSION}.zip"

          echo "::set-output name=version::$VERSION"
          echo "::set-output name=changelog::$CHANGELOG"
          echo "::set-output name=artifact::$ARTIFACT"

      - name: Build the plugin distribution
        run: gradle buildPlugin

      # Upload plugin artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: plugin-artifact
          path: ./build/distributions/${{ needs.build.outputs.artifact }}


      # Cache verification IDEs
      - name: Setup Plugin Verifier IDE Dependencies Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.pluginVerifier
          key: ${{ runner.os }}-pluginverifiertask
#          key: ${{ runner.os }}-pluginverifier-ides-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      - name: Verify Plugin
        run: gradle runPluginVerifier
