name: Build & Test
on: [push, pull_request]

jobs:

  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest

    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3


  build:
    name: Build, Test & Validate Plugin
    needs: gradleValidation
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk8

    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run plugin tests
        run: gradle check

      - name: Build the plugin distribution
        run: gradle buildPlugin

      - name: Verify Plugin
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
        with:
          ide-versions: |
            ideaIC:2019.3.5
            ideaIC:2020.1.4
            ideaIC:2020.2.3
            ideaIC:LATEST-EAP-SNAPSHOT
      - name: Plugin Verifier Output
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
